import { assets } from "./Assets";

export const products = [
    {
        id: 1,
        name: "Clownfish Pair",
        price: 89.99,
        category: "Live Fish",
        rating: 4.9,
        reviews: 127,
        image: assets.img1_1,
        badge: "Best Seller",
    },
    {
        id: 2,
        name: "Neon Tetra (6-pack)",
        price: 24.99,
        category: "Live Fish",
        rating: 4.7,
        reviews: 89,
        image: assets.img1_2,
        badge: "Sale",
    },
    {
        id: 3,
        name: "Marine Tank Starter Kit",
        price: 299.99,
        category: "Aquariums",
        rating: 4.8,
        reviews: 64,
        image: assets.img1_3,
        badge: "New",
    },
    {
        id: 4,
        name: "Premium Coral Food",
        price: 19.99,
        category: "Food & Care",
        rating: 4.6,
        reviews: 43,
        image: assets.img1_4,
        badge: null,
    },
    {
        id: 5,
        name: "LED Reef Lighting System",
        price: 159.99,
        category: "Equipment",
        rating: 4.9,
        reviews: 112,
        image: assets.img1_5,
        badge: "Top Rated",
    },
    {
        id: 6,
        name: "Live Rock Set (5lbs)",
        price: 39.99,
        category: "Decor",
        rating: 4.5,
        reviews: 78,
        image: assets.img1_6,
        badge: null,
    },
    {
        id: 7,
        name: "Protein Skimmer",
        price: 189.99,
        category: "Equipment",
        rating: 4.7,
        reviews: 56,
        image: assets.img1_7,
        badge: null,
    },
    {
        id: 8,
        name: "Royal Gramma",
        price: 34.99,
        category: "Live Fish",
        rating: 4.8,
        reviews: 34,
        image: assets.img1_8,
        badge: "Sale",
    },
    {
        id: 9,
        name: "Aquascaping Tool Kit",
        price: 44.99,
        category: "Equipment",
        rating: 4.4,
        reviews: 92,
        image: assets.img1_9,
        badge: null,
    },
];